### ISSUE TITLE
Issue in GlobalVariable

### ISSUE THREAD

**Issue by pradeepiisc** [rahulgurnani/SensorSdk#3]
private void performLogin(User user) {
        Context context = getApplicationContext();

        globalVariable = GlobalVariable.getInstance();
        globalVariable.setUser(user);
        globalVariable.setContext(context);
        SyncUtils.CreateSyncAccount(this);
        SyncAdapter.performSync();
        if (!(dataStoreHelper.getSleepData().getSu() && dataStoreHelper.getSleepData().getEu())) {
            scheduleNotification();
        }
        startActivity(new Intent(MainActivity.this, ViewDataActivity.class));
        finish();

    }

In above Function performLogin(...) , when you try to get the instance of GlobalVariable, getContext() is called before setting the context which is done after getting the instance. 
I have resolved it by setting the firebase parameter outside the private constructor so that the context is set first and then firebase params are set using the context parameter.

**Comment by rahulgurnani** [comment]
Yeah it's a bug, thanks pointing it out

**Comment by rahulgurnani** [comment]
Wanted you to add you as a reviewer for the pull request for this issue
https://github.com/rahulgurnani/SensorSdk/pull/5
